In 2618
getyoti/yoti-sign-examples pull request #1
Opened 2020-05-12 13:33 UTC by nikhilPank

2020-05-21 09:16 UTC, LAFYoti commented on javascript/README.md
> +- Add a PDF to /documents and configure the options object in /routes/createEnvelope.js
Maybe specify the name of the PDF to be example.pdf

2020-05-21 09:16 UTC, LAFYoti commented on javascript/README.md
> +- Add a PDF to /documents and configure the options object in /routes/createEnvelope.js
Maybe specify the name of the PDF to be example.pdf

2020-05-22 10:00 UTC, jlmartyres requested changes

2020-05-22 10:00 UTC, jlmartyres commented on javascript/package.json
> +    "hbs": "~4.0.4",
Update hbs to 4.1.1 to fix npm issues on install

2020-05-22 10:00 UTC, jlmartyres commented on javascript/README.md
> +- Run the project with `npm start` or `nodemon`
Let's remove nodemon as it assumes a global install

2020-05-22 10:00 UTC, jlmartyres commented on javascript/README.md
> +- Create a .env file using the example `.env.example` file
Would be easier to say, rename .env.example to .env

2020-05-22 10:00 UTC, jlmartyres commented on javascript/bin/www
> +  debug('Listening on ' + bind);
Change debug to console.log

2020-05-22 10:00 UTC, jlmartyres commented on javascript/bin/www
> +var debug = require('debug')('node-sign-example:server');
Remove debug line

2020-05-22 10:00 UTC, jlmartyres commented on javascript/package.json
> +    "debug": "~2.6.9",
remove debug from dependencies

2020-05-22 10:00 UTC, jlmartyres commented on javascript/package.json
> +    "cookie-parser": "~1.4.4",
I don't think this project is parsing cookies so this can be removed

2020-05-22 10:00 UTC, jlmartyres commented on javascript/app.js
> +const cookieParser = require("cookie-parser");
Remove cookieParser import

2020-05-22 10:00 UTC, jlmartyres commented on javascript/app.js
> +app.use(cookieParser());
Remove cookieParser middleware

2020-05-22 10:00 UTC, jlmartyres commented on javascript/README.md
> +- Add a PDF to /documents and configure the options object in /routes/createEnvelope.js
Github removes empty folders so /documents doesn't exist - would it be possible to add a sample dummy PDF as a placeholder and reference this by default? This is a useful one https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/createEnvelope.js
> +      file: fs.createReadStream("documents/example.pdf"), // file system location of PDF
It might be neater to references this path in the .env for the sake of the example, and by default set this to a sample PDF inside of documents/.

It is worth using path.join for file paths

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/archiveEnvelope.js
> +  return rp(envelope)
For all of these methods which return a promise, you can just do return rp(envelope) or return rp(options). It's best to handle the responses and catch the errors while running the function

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/createEnvelope.js
> +  return rp(envelope)
Just return rp(envelope) here

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/createEnvelope.js
> +  let result = await createEnvelope();
Surround this await call in a try catch to handle success and errors

```router.get("/", async function (req, res, next) {
  try {
    let result = await createEnvelope();
    console.log(result);
    let envelopeid = JSON.parse(result).envelope_id;
    res.render("index", { envelopeid });
  } catch (error) {
    console.log(error.message);
    res.render("error", error);
  }
});

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/createEnvelope.js
> +  let envelopeid = JSON.parse(result).envelope_id;
You can avoid JSON.parse by setting json: true in the request promise options, since we know the response being returned is JSON

2020-05-22 10:00 UTC, jlmartyres commented on javascript/routes/archiveEnvelope.js
> +  let result = await archiveEnvelope(envelopeid);
see comments for create envelope

2020-06-03 08:57 UTC, jlmartyres commented
Could you remove .DS_Store? It's in the gitignore but still appears to be in the root directory

2020-06-04 08:26 UTC, nikhilPank commented
> Could you remove .DS_Store? It's in the gitignore but still appears to be in the root directory

Done

2020-06-04 08:42 UTC, jlmartyres approved these changes

2020-06-04 08:53 UTC, merged